services:
  crowdsec:
    image: ghcr.io/klementng/docker-crowdsec:main
    container_name: crowdsec
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - COLLECTIONS=crowdsecurity/nginx #...
      - LOCAL_API_URL=http://127.0.0.1:55555 # bind to the following port
      - PROMETHEUS_ENABLED=true
      - PROMETHEUS_LEVEL=full
      - PROMETHEUS_LISTEN_ADDR=127.0.0.1
      - PROMETHEUS_LISTEN_PORT=6060
    volumes:
      - ./crowdsec/config:/etc/crowdsec
      - ./crowdsec/data:/var/lib/crowdsec/data/
    userns_mode: host
    network_mode: host
    restart: unless-stopped
