services:
  
  crowdsec:
    image: ghcr.io/klementng/docker-crowdsec:main
    cap_add:
      - NET_ADMIN
    environment:
      - LOCAL_API_URL=http://0.0.0.0:8888
    volumes:
      - ./config:/etc/crowdsec
    network_mode: host

  test:
    build: .
    cap_add:
      - NET_ADMIN
    environment:
      - LOCAL_API_URL=http://0.0.0.0:8888
    volumes:
      - ./config:/etc/crowdsec